# Generated by Django 5.1.1 on 2024-09-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('division', models.CharField(choices=[('social', 'Social'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('preferred_game_time', models.CharField(choices=[('Mid', 'Mid'), ('Late', 'Late'), ('Flexible', 'Flexible')], max_length=50)),
                ('t_shirts', models.CharField(choices=[('None ($0)', 'None ($0)'), ('Cotton ($75)', 'Cotton ($75)'), ('Dri-Fit ($100)', 'Dri-Fit ($100)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.teaminfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('co_first_name', models.CharField(max_length=200)),
                ('co_last_name', models.CharField(max_length=200)),
                ('co_email', models.EmailField(max_length=200)),
                ('co_phone', models.CharField(max_length=11)),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.teaminfo')),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.teaminfo')),
            ],
        ),
    ]
